#%RAML 1.0
title: email-poc-proc
version: v1
mediaType: [application/json,application/xml]

/send_mail:
  post:
    description: post  data to system layer
    displayName: Send Mail
    headers:
      appName:
        description: name of the app
        type: string
        required: true
    queryParameters:
      dataType:
        description: type of data(xml/json)
        type: string
        required: true
        enum:
          - useJSON
          - useXML
    responses:
      200:
        body:
          application/json:
            example: "Data send to mail successfully"
      404:
        body:
          application/json:
            example: "mail not send"
