#%RAML 1.0 NamedExample
example:
  {
  "Person": [
    {
      "ID": "1745309",
      "FirstName": "michael",
      "MiddleName": null,
      "LastName": "johnston",
      "MaidenName": null,
      "Title": null,
      "DateOfBirth": "1972-03-27",
      "BirthCountry": "Trinidad and Tobago",
      "MaritalStatus": "S",
      "SmokerStatus": "N",
      "Gender": "M",
      "CompanyName": null,
      "ClientMDMID": "1745309",
      "PrimaryOccupation": "video camera editor",
      "EmployerName": "republic bank",
      "EmployerAddress1": "park street  , Port of Spain,",
      "EmployerAddress2": "",
      "EmployerAddress3": "",
      "EmployerCity": "",
      "EmployerState": "",
      "EmployerCountry": "",
      "TotalAnnualIncome": null,
      "OccupationalIncome": "110000",
      "OtherIncome": null,
      "PrimaryEmail": "janeal.james@myguardiangroup.com",
      "SecondaryEmail": null,
      "HomeAddress1": "get st",
      "HomeAddress2": null,
      "HomeAddress3": null,
      "HomeCity": "Freeport",
      "HomeState": "",
      "HomeCountry": "Trinidad and Tobago",
      "HomeZipCode": null,
      "MailingAddress1": "",
      "MailingAddress2": "",
      "MailingAddress3": "",
      "MailingCity": "",
      "MailingState": "",
      "MailingCountry": "",
      "MailingZipCode": "",
      "HomePhone": "",
      "CellPhone1": "1111111111",
      "CellPhone2": null,
      "WorkPhone": "",
      "ProofOfAgeIndicator": "Yes",
      "YearsEmployed": "4",
      "SelfEmployed": false,
      "IsGHLEmployee": false,
      "IsPep": false,
      "Identification": [
        {
          "IDNumber": "234322",
          "IDType": "Passport",
          "IDExpDate": "2023-04-30 00:00:00.0",
          "IssueCountry": null
        }
      ]
    }
  ],
  "Application": {
    "ApplicationID": "C03EEAF6-B3D9-4E82-9F6F-869DFB4F1332",
    "UniqueApplicationID": "",
    "RegionCode": "TT",
    "NewBusiniess": [
      {
        "Type": "Sales Source",
        "Value": "New"
      }
    ],
    "ApplicationAgent": [
      {
        "AgentCode": "AXXXX4",
        "Split": "100",
        "IsPrimary": "false"
      }
    ],
    "BankAccountInfo": {
      "AccountNumber": "",
      "AccountType": "",
      "Country": null,
      "BankName": "",
      "BranchName": "",
      "BranchNumber": null,
      "TransitNumber": null,
      "RoutingNumber": "",
      "DrawDay": "0"
    },
    "UserNTID": null,
    "CreateDate": null,
    "SubmitDate": null,
    "StatusID": null,
    "SumAssured12MonthAgent": null,
    "PayorCompanyName": null,
    "OwnerTypeCode": null,
    "OwnerCompanyName": null,
    "ApplicantTypeCode": null,
    "RaterOccupation": null,
    "RaterAge": null,
    "RaterIncome": null,
    "RaterPremium": null,
    "RaterPremiumFrequency": null,
    "RaterStabilityEmployment": null,
    "RaterInitialSettlement": null,
    "RaterPreviousInsurance": null,
    "TotalRater": null,
    "ApplicationDetailValue": null
  },
  "Policy": [
    {
      "InsuredId": "1745309",
      "PolicyID": null,
      "OwnerID": "1745309",
      "PayorID": "1745309",
      "OwnerRelationshipName": null,
      "BeneficiaryIsEstate": null,
      "BeneficiaryIsIrrevocable": null,
      "BeneficiaryIsMPA": null,
      "ProductCode": "CRIEV1",
      "IngeniumPolicyID": "5003613881",
      "ApplicationSignedDate": "2023-04-17",
      "EffectiveDate": "2022-05-03",
      "InterestHandling": null,
      "SecondaryInsured": [],
      "BeneficiaryInfo": [],
      "PolicyOptions": [
        {
          "OptionName": "Sum Assured",
          "PolicyOptionValue": "190000"
        },
        {
          "OptionName": "Method of Payment",
          "PolicyOptionValue": "B"
        },
        {
          "OptionName": "Mode of Payment",
          "PolicyOptionValue": "01"
        },
        {
          "OptionName": "Base Premium Amount",
          "PolicyOptionValue": "570.95"
        },
        {
          "OptionName": "Listbill",
          "PolicyOptionValue": ""
        }
      ],
      "Coverages": [
        {
          "ProductCode": "CRIEV1",
          "ProductName": "CRIEV1 - Life Evol Rej TT",
          "Premium": "570.95",
          "FaceAmount": "190000",
          "InsuredID": "1745309",
          "Decision": null,
          "EffectiveDate": null,
          "MaturityDate": null,
          "PremiumChangeDate": null,
          "Rating1": 0,
          "RatingReason1": "Medical Reasons",
          "Rating2": 0,
          "RatingReason2": "",
          "PermFlatExtraAmt": 3,
          "TempFlatExtraAmt": 0,
          "TempFlatExtraDuration": 0,
          "Funds": [],
          "Disposition": {
            "Value": "Approved",
            "Reason": "Approve with a Rating"
          }
        }
      ],
      "Disposition": null
    }
  ]
}
