#%RAML 1.0 NamedExample
getIngenium-example:
   {
    "Output": {
        "IngeniumPolicyID": "5003613881",
        "Status": "File Closed",
        "ClientInfoList": [
            {
                "FirstName": "MICHAEL",
                "LastName": "JOHNSTON",
                "ClientID": "1745309",
                "DateOfBirth": "1972-03-27"
            },
            {
                "FirstName": "SELINA",
                "LastName": "HANEY",
                "ClientID": "1703071",
                "DateOfBirth": "1991-09-04"
            }
        ]
    },
    "Result": {
        "Success": true
    }
   }